version: "3.7"

services:
  airflow:
    image: jam717/airflow-app
    #restart: always
    depends_on:
      - mysql
    ports:
      - 8080:8080
    volumes:
      - ./airflow:/usr/local/airflow/
      - restaurant-data:/airflow-app/data/
    environment:
      # load examples - default set to no
      LOAD_EX: n
      EXECUTOR: Local
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY

  mysql:
    image: mysql:5.7
    container_name: airflow_mysql_db
    volumes:
      - airflow-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: airflow
      MYSQL_USER: airflow
      MYSQL_PASSWORD: airflow
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --explicit_defaults_for_timestamp=1

volumes:
  restaurant-data:
  airflow-mysql-data:
